/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package api.gateway;


import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;

public class RepeatedWord implements RequestHandler<String, String> {

    @Override
    public String handleRequest(String input, Context context) {
        context.getLogger().log("Input: " + input);

        // TODO: implement your handler
        return findRepeatedWord(input);
    }

    public static String findRepeatedWord(String input) {
        if (input == null) {
            return null;
        }
        String[] words = input.toLowerCase().split(" ");
        Hashtable wordHash = new Hashtable();

        for (int i = 0; i < words.length; i++) {
            String singleWord = words[i].replaceAll("[^\\w\\s]+$", "");
            if (wordHash.contains(singleWord)) {
                return singleWord;
            } else {
                wordHash.add(singleWord, "");
            }
        }
        return null;
    }

}